### ISSUE TITLE
[Bug]: azure-tools/typespec-autorest crashes: Cannot read properties of undefined (reading 'stateMap'

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/typespec-azure#1292]
### Describe the bug

azure-tools/typespec-autorest crashes when trying to build out a commit from the azure-rest-api-specs repo for OpenAI.

Stack trace (I used <root> instead of my local path, but it's otherwise unchanged):

```
Emitter "@azure-tools/typespec-autorest" crashed! This is a bug.
Please file an issue at https://github.com/Azure/typespec-azure/issues
 
TypeError: Cannot read properties of undefined (reading 'stateMap')
    at getScopedDecoratorData (<root>/sdk/ai/azopenai/testdata/node_modules/@azure-tools/typespec-client-generator-core/dist/src/decorators.js:13:36)
    at shouldFlattenProperty (<root>/sdk/ai/azopenai/testdata/node_modules/@azure-tools/typespec-client-generator-core/dist/src/decorators.js:732:12)
    at applyIntrinsicDecorators (<root>/sdk/ai/azopenai/testdata/node_modules/@azure-tools/typespec-autorest/dist/src/openapi.js:1515:13)
    at getOpenAPI2Parameter (<root>/sdk/ai/azopenai/testdata/node_modules/@azure-tools/typespec-autorest/dist/src/openapi.js:879:27)
    at resolveHost (<root>/sdk/ai/azopenai/testdata/node_modules/@azure-tools/typespec-autorest/dist/src/openapi.js:166:27)
    at getOpenAPIForService (<root>/sdk/ai/azopenai/testdata/node_modules/@azure-tools/typespec-autorest/dist/src/openapi.js:45:12)
    at getAllServicesAtAllVersions (<root>/sdk/ai/azopenai/testdata/node_modules/@azure-tools/typespec-autorest/dist/src/emit.js:101:38)
    at emitAllServiceAtAllVersions (<root>/sdk/ai/azopenai/testdata/node_modules/@azure-tools/typespec-autorest/dist/src/emit.js:113:28)
    at Object.$onEmit [as emitFunction] (<root>/sdk/ai/azopenai/testdata/node_modules/@azure-tools/typespec-autorest/dist/src/emit.js:16:11)
    at runEmitter (<root>/sdk/ai/azopenai/testdata/node_modules/@typespec/compiler/dist/src/core/program.js:452:27)
```

Package.json dependencies:

```json
  "dependencies": {
    "@azure-tools/typespec-autorest": "0.44.0",
    "@azure-tools/typespec-azure-core": "0.44.0",
    "@typespec/compiler": "0.58.0",
    "@typespec/openapi3": "0.58.0"
  }
```

### Reproduction

I uploaded a standalone version of this project here:
https://github.com/richardpark-msft/openai-gen-bug

I apologize that it's not small, but it does demonstrate the problem readily. I added a 'repro' command script, so you can just do:

```
npm run repro
```
And you'll get the error.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by richardpark-msft** [comment]
@tadelesh, assigned it to you (@jhendrixMSFT thought you'd make sense as the owner).

**Comment by tadelesh** [comment]
please upgrade `@azure-tools/typespec-autorest` to `0.44.1`.
