### ISSUE TITLE
[Bug] [TCGC] unknown format

### ISSUE THREAD

**Issue by msyyc** [Azure/typespec-azure#214]
When trying to generate Python SDK for [NetworkAnalytics.Management](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/networkanalytics/NetworkAnalytics.Management), the following error happens:
```
Please file an issue at https://github.com/Azure/autorest.python/issues

Error: Unknown format arm-id
    at addFormatInfo (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:48:23)
    at getClientType (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:533:17)
    at getSdkModelPropertyType (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:632:24)
    at getSdkBodyModelPropertyType (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:652:18)
    at addPropertiesToModelType (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:681:32)
    at getSdkModel (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:382:9)
    at getClientType (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:524:24)
    at getSdkModelPropertyType (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:632:24)
    at getSdkBodyModelPropertyType (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:652:18)
    at addPropertiesToModelType (file:///D:/dev/azure-sdk-for-python/sdk/networkanalytics/azure-mgmt-networkanalytics/TempTypeSpecFiles/NetworkAnalytics.Management/node_modules/@azure-tools/typespec-client-generator-core/dist/src/types.js:681:32)

--------------------------------------------------
Library Version                0.19.0
TypeSpec Compiler Version      0.52.0
--------------------------------------------------
```
I infer it is related with https://github.com/Azure/typespec-azure/blob/ebfe63960277356c611f15b2404a0ae6f2d9e6ed/packages/typespec-azure-resource-manager/lib/models.tsp#L101

**Comment by tadelesh** [comment]
`@format` should not be identified with build-in types anymore. We will change this logic soon.
