### ISSUE TITLE
[Bug]: Emitter "@azure-tools/typespec-autorest" crashed!

### ISSUE THREAD

**Issue by juyoung98** [Azure/typespec-azure#595]
### Describe the bug

Emitter "@azure-tools/typespec-autorest" crashed! This is a bug.
Please file an issue at https://github.com/Azure/typespec-azure/issues

TypeError: Cannot read properties of undefined (reading 'values')
    at walkPropertiesInherited (file:///mnt/vss/_work/1/s/node_modules/@typespec/compiler/dist/src/core/checker.js:4731:51)
    at walkPropertiesInherited.next (<anonymous>)
    at countPropertiesInherited (file:///mnt/vss/_work/1/s/node_modules/@typespec/compiler/dist/src/core/checker.js:4743:16)
    at getEffectiveModelType (file:///mnt/vss/_work/1/s/node_modules/@typespec/compiler/dist/src/core/checker.js:4655:39)
    at Object.getEffectivePayloadType (file:///mnt/vss/_work/1/s/node_modules/@typespec/http/dist/src/metadata.js:403:31)
    at getSchemaOrRef (file:///mnt/vss/_work/1/s/node_modules/@azure-tools/typespec-autorest/dist/src/openapi.js:619:29)
    at emitEndpointParameters (file:///mnt/vss/_work/1/s/node_modules/@azure-tools/typespec-autorest/dist/src/openapi.js:732:19)
    at emitOperation (file:///mnt/vss/_work/1/s/node_modules/@azure-tools/typespec-autorest/dist/src/openapi.js:414:9)
    at Array.forEach (<anonymous>)
    at emitOpenAPIFromVersion (file:///mnt/vss/_work/1/s/node_modules/@azure-tools/typespec-autorest/dist/src/openapi.js:223:20)

### Reproduction

import "@typespec/http";
import "@azure-tools/typespec-client-generator-core";

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by juyoung98** [comment]
had to add some missing @added decorators
