### ISSUE TITLE
[Bug]: TCGC error on easm commit=11dd0dbfb9bec989f3a9a3536ae526407ff17c78

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#626]
### Describe the bug

TCGC version 0.41.0
https://github.com/Azure/azure-sdk-for-java/blob/73e05c8ddef09dd15e6904236ed02cd63d0d4baa/eng/emitter-package.json#L13

Error message

```
Error: Can't find corresponding parameter for dataConnectionData out of apiVersion, name, content, frequency, frequencyOffset
    at getCorrespondingMethodParams (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/http.js:318:15)
    at getSdkHttpParameters (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/http.js:75:54)
    at getSdkHttpOperation (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/http.js:12:41)
    at getSdkServiceOperation (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/package.js:17:51)
    at getSdkBasicServiceMethod (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/package.js:137:47)
    at getSdkServiceMethod (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/package.js:170:12)
    at getSdkMethods (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/package.js:242:38)
    at createSdkClientType (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/package.js:350:38)
    at getSdkPackage (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/package.js:372:9)
    at createSdkContext (file:///C:/github/azure-sdk-for-java/sdk/easm/azure-analytics-defender-easm/TempTypeSpecFiles/Easm/node_modules/@azure-tools/typespec-client-generator-core/dist/src/decorators.js:402:42)
```

### Reproduction

https://github.com/Azure/azure-sdk-for-java/blob/73e05c8ddef09dd15e6904236ed02cd63d0d4baa/sdk/easm/azure-analytics-defender-easm/tsp-location.yaml

Run `tsp-client update` in that folder.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by weidongxu-microsoft** [comment]
The error would disappear if I use latest spec commit (20e26266be77e6da4321259fb79e51e8281e48b2).

**Comment by tadelesh** [comment]
resolved by: https://github.com/Azure/typespec-azure/pull/630
