### ISSUE TITLE
[Bug][getAllOperations] Exception when defining a `utcDateime` parameter

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#64]
**Describe the bug**

In `autorest.csharp`, we have a test which defines a `utcDatetime` parameter: https://github.com/Azure/autorest.csharp/blob/74938fddeede57bd4758720b05ea355eabd29645/test/TestProjects/sdk/newprojecttypespec/Azure.NewProject.TypeSpec/Azure.NewProject.TypeSpec.tsp#L292

```typescript
op addTimeHeader(
    @header("Repeatability-First-Sent") repeatabilityFirstSent?: utcDateTime 
): void;
```

Adopting tcgc on `getAllOperations` branch, and there will be an exception when compiling the test.
```
Error: Unknown format date
    at addFormatInfo (file:///C:/Users/mingzhehuang/workspaces/archerzz/typespec-azure/packages/typespec-client-generator-core/src/types.ts:146:15)
    at getSdkModelPropertyType (file:///C:/Users/mingzhehuang/workspaces/archerzz/typespec-azure/packages/typespec-client-generator-core/src/types.ts:850:3)
    at file:///C:/Users/mingzhehuang/workspaces/archerzz/typespec-azure/packages/typespec-client-generator-core/src/package.ts:451:17
    at Array.map (<anonymous>)
    at getSdkBasicServiceMethod (file:///C:/Users/mingzhehuang/workspaces/archerzz/typespec-azure/packages/typespec-client-generator-core/src/package.ts:451:6)
    at getSdkServiceMethod (file:///C:/Users/mingzhehuang/workspaces/archerzz/typespec-azure/packages/typespec-client-generator-core/src/package.ts:500:10)
    at getSdkMethods (file:///C:/Users/mingzhehuang/workspaces/archerzz/typespec-azure/packages/typespec-client-generator-core/src/package.ts:613:17)
    at createSdkClientType (file:///C:/Users/mingzhehuang/workspaces/archerzz/typespec-azure/packages/typespec-client-generator-core/src/package.ts:653:14)
    at getSdkPackage (file:///C:/Users/mingzhehuang/workspaces/archerzz/typespec-azure/packages/typespec-client-generator-core/src/package.ts:673:5)
    at createSdkContext (file:///C:/Users/mingzhehuang/workspaces/archerzz/typespec-azure/packages/typespec-client-generator-core/src/decorators.ts:487:27)

```

**To Reproduce**
Build the test project in `autorest.csharp`, using a generator built with TCGC on `getAllOperations` branch.

**Expected behavior**
There should be no exception.

**Additional context**

**Comment by archerzz** [comment]
There is another question for compiler. For `utcDatetime`, why do we get `date` as the result of `getFormat`? Shouldn't it be `date-time`?
